services:
  db:
    image: postgis/postgis:17-3.5
    container_name: lootopia-db
    restart: always
    environment:
      POSTGRES_USER: lootopia
      POSTGRES_PASSWORD: lootopia_dev_2026
      POSTGRES_DB: lootopia
    ports:
      - "5432:5432"
    volumes:
      - lootopia_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lootopia"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Lootopia.Api
      dockerfile: Dockerfile
    container_name: lootopia-api
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=lootopia;Username=lootopia;Password=lootopia_dev_2026
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./Lootopia.Client
      dockerfile: Dockerfile
    container_name: lootopia-client
    restart: always
    ports:
      # 8081 et non 80 : sur le VPS, Caddy occupe le port 80 et proxifie :80 -> 127.0.0.1:8081
      - "8081:80"
      - "3000:80"
    depends_on:
      - api

volumes:
  lootopia_pgdata:
